import Head from "next/head";
import SearchBanner from "@/components/SearchBanner";
import Item from "@/components/Item";
import Category from "@/components/Category";
import { useEffect, useRef, useState } from "react";
import WelcomeModal from "@/utils/modals/WelcomeModal";
import { useGetLatestProductsQuery } from "@/redux/features/products/productApi";

export default function Home({ categories }) {
  const { data, isLoading } = useGetLatestProductsQuery();
  // console.log(data);
  const welcomeModal = useRef(null);
  const [isWelcomeModal, setIsWelcomeModal] = useState(null);

  const handleCloseModal = () => {
    localStorage.removeItem("welcomeModal");
  };

  useEffect(() => {
    const data = localStorage.getItem("welcomeModal");
    if (data) {
      setIsWelcomeModal(JSON.parse(data));
      welcomeModal.current.click();
    }
  }, []);

  return (
    <>
      <Head>
        <title>Turkey Trade Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <div className="home">
        <SearchBanner />
        <Category categories={categories} />
        <div className="container mt-8">
          <Item items={data?.data} isLoading={isLoading} />
        </div>

        <button
          ref={welcomeModal}
          className="btn btn-primary d-none"
          data-bs-target="#exampleModalToggle1"
          data-bs-toggle="modal"
        >
          Open first modal
        </button>
      </div>

      <WelcomeModal />
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    `${process.env.REACT_APP_SERVER_URI}/categories/show/cate`
  );
  const categories = await res.json();
  return {
    props: {
      categories: categories.data,
    },
  };
}
