import Head from "next/head";
import SearchBanner from "@/components/SearchBanner";
import Item from "@/components/Item";
import Category from "@/components/Category";
import { useEffect, useRef, useState } from "react";
import WelcomeModal from "@/utils/modals/WelcomeModal";
import { useGetLatestProductsQuery } from "@/redux/features/products/productApi";
import PopularProducts from "@/components/home/PopularProducts";

export default function Home() {
  const { data, isLoading } = useGetLatestProductsQuery();
  const welcomeModal = useRef(null);
  const [isWelcomeModal, setIsWelcomeModal] = useState(null);

  // useEffect(() => {
  //   window.scrollTo({
  //     top: 0,
  //     behavior: "smooth", // Set behavior to 'smooth' for smooth scrolling
  //   });
  // }, []);

  useEffect(() => {
    const data = localStorage.getItem("welcomeModal");
    if (data) {
      setIsWelcomeModal(JSON.parse(data));
      welcomeModal.current.click();
    }
  }, []);

  return (
    <>
      <Head>
        <title>Turkey Trade Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <div className="home">
        <SearchBanner />
        <Category />
        <div className="container mt-8">
          <h1 className="label mb-3">Recently Listed</h1>
          <Item items={data?.data} isLoading={isLoading} />
          <PopularProducts />
        </div>

        <button
          ref={welcomeModal}
          className="btn btn-primary d-none"
          data-bs-target="#exampleModalToggle1"
          data-bs-toggle="modal"
        >
          Open first modal
        </button>
      </div>

      <WelcomeModal />
    </>
  );
}

// export async function getServerSideProps() {
//   const res = await fetch(`${base_url}/categories/all/cate`);
//   const categories = await res.json();

//   return {
//     props: {
//       categories: categories.data,
//     },
//   };
// }
